spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3316/zst?characterEncoding=utf8
    username: root
    password: 123456
#  redis:
#    host: 127.0.0.1
#    port: 6379
  cache:
    ehcache:
      config: "classpath:ehcache.xml"
#    cache-names: "order"
#    redis:
#      time-to-live: "10m"
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  cache-enabled: true